### ISSUE TITLE
Image Transfer Issue from Ecommerce Admin to Ecommerce Retail Store

### ISSUE THREAD

**Issue by Buyaki01** [Buyaki01/nextjs13-online-store-shop#3]
### Description:
We are currently sharing a database between our e-commerce admin and retail store systems. One challenge we're facing is the efficient transfer of images from the public/images directory of the ecommerce admin repository to the public/images directory of the ecommerce retail store. We need a seamless solution to ensure these images are accessible to retail customers.

### Problem Description:
Images are stored in the public/images directory of the ecommerce admin.
We require an effective way to transfer these images to the public/images directory of the e-commerce retail store.

### Steps to Reproduce:
- Access the eCommerce admin system.
- Navigate to the public/images directory in the admin repository.
- Review the images available in this directory.
- Outline the necessary steps to transfer these images to the e-commerce retail store's public/images directory.

### Expected Behavior:
The images should be successfully transferred from the admin repository to the retail store's repository and be readily accessible to retail customers.

### Actual Behavior:
Currently, we do not have an established process for transferring images between the repositories.

### Additional Information:
We have tried manually copying the images, but this is neither efficient nor sustainable. We need a more automated or scalable approach. Both repositories are hosted on GitHub.

**Comment by kanishak11-cyber** [comment]
you can use the AWS S3 for storing the images and it will generate a link you can call the images on both side with the help of link
